language: python
addons:
  postgresql: "9.6"
services:
  - postgresql
python:
  - "3.6"
install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install --dev
script:
  - coverage erase
  - pytest --cov --cov-report= --junitxml=junit.xml
  - coverage xml -o coverage.xml
after_success:
  - coveralls